### ISSUE TITLE
Allow the configure the etcd package name

### ISSUE THREAD

**Issue by rtoma** [cristifalcas/puppet-etcd#14]
Redhat has named its etcd v3 package etcd3: https://rhn.redhat.com/errata/RHEA-2016-2621.html

Your (excellent!) puppet code uses 'etcd' as hardcoded package name.

We currently use the manage_package=false trick, but wouldn't it be nice to set package_name=etcd3 and let your install.pp do its job?

Regards.

**Comment by cristifalcas** [comment]
Fixed in the latest release.
