### ISSUE TITLE
/usr/share/puppet/modules/etcd/manifests/init.pp:237 validate_integer invalid function

### ISSUE THREAD

**Issue by discodex** [cristifalcas/puppet-etcd#3]
Module is broke as it has a function that is listed as an invalid function:

/usr/share/puppet/modules/etcd/manifests/init.pp:237

validate_integer needs to be changed to validate_array (per: https://puppetlabs.com/blog/module-of-the-week-puppetlabs-stdlib-puppet-labs-standard-library-part-2)

After changing that, works like a charm!

**Comment by cristifalcas** [comment]
The function validate_integer was added in stdlib 4.6.0. I will update the dependencies to require this version at least.

**Comment by cristifalcas** [comment]
Fixed by depending on a recent enough stdlib module
