### ISSUE TITLE
List of supported OS versions for Red Hat OS family is out of date

### ISSUE THREAD

**Issue by ASBishop** [cristifalcas/puppet-etcd#34]
Currently, the code that validates the Red Hat OS version is structured in a way that requires a code change each time a new fedora or EL version is released. The code has not been kept up to date, and doesn't recognize fedora > 26 or EL > 7.

I plan to submit a pull request that addresses this.

**Comment by cristifalcas** [comment]
Hi @ASBishop , unfortunately I don't have time to maintain this module anymore.

If you want to take care of it, plase fork it and send me a link to your project. I will add a message on the readme that this module is deprecated and point to yours instead.

**Comment by ASBishop** [comment]
Thank you for accepting my pull request. I'll need to work with my employer to determine how to proceed now that you aren't able to continue maintaining the code.

**Comment by jeckersb** [comment]
Hey!

I'm planning to take this over instead of Alan if you'd like.  I went ahead and created an org for the project and forked it here:

https://github.com/puppet-etcd/puppet-etcd
