### ISSUE TITLE
no parameter named 'etcd_listen_client_urls' 

### ISSUE THREAD

**Issue by olevole** [cristifalcas/puppet-etcd#36]
'clean' CentOS Linux release 7.7.1908 (Core) installation
puppet client: puppet-agent-6.9.0-1.el7.x86_64

I try to use a simple configuration from 'Basic usage:':

```
 class { 'etcd':
    ensure                     => 'latest',
    etcd_listen_client_urls    => 'http://0.0.0.0:2379',
  }
```

result:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Etcd]: has no parameter named 'etcd_listen_client_urls' (file: /etc/puppetlabs/code/environments/production/modules/k8smaster_node/manifests/init.pp, line: 11, column: 3) on node k8smaster1.fbs.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by cristifalcas** [comment]
Seems like a the documentation is wrong. It should be `listen_client_urls`

I want to let you know that I will archive this repo, as I don't work with puppet anymore.

Please open a bug at https://github.com/puppet-etcd/puppet-etcd for a fix
