### ISSUE TITLE
etcd::config not detecting Centos7

### ISSUE THREAD

**Issue by GKTheOne** [cristifalcas/puppet-etcd#7]
The `$::osfamily` and `$::operatingsystemmajrelease` reported by puppet when operating on a Centos7 node is 'RedHat' & '7' respectively, however I needed to change the etcd::config case match to a string (by single quoting the 7) before it would detect Centos7 properly.

(I am unsure why, and can't find anything on google relevant to this issue, so just a heads up)

**Comment by cristifalcas** [comment]
done
