### ISSUE TITLE
template variable scope issue

### ISSUE THREAD

**Issue by GKTheOne** [cristifalcas/puppet-etcd#8]
I'm hoping for some general puppet usage advice because the etcd.conf template is finding the right values when using the "scope" notation, but not when using the "@variable" notation. eg, I set a cors value and it does not appear in the template unless I remove the "@cors" test.

I'm using Puppet Enterprise 2015.3 as my dev environment. Do you think it's possible I've screwed a setting somewhere that can affect this? (And where/which one?)

**Comment by GKTheOne** [comment]
I should also qualify that I am "resource-like" (is that the right term) including the ::etcd module.
eg:

```
class profile::my_thing::etcd( ... ) {
  # set some variables - nothing else
  class { '::etcd':
    # explicitly set all parameters
  }
}
```

**Comment by GKTheOne** [comment]
I thought it was something on my end, but it looks like it is due to the etcd class variables not being in the etcd::config scope. Sorry :)

**Comment by cristifalcas** [comment]
I tested this and it works as expected.

Can you give an example on how are you defining the etcd class?

What puppet version are you using?

**Comment by GKTheOne** [comment]
I'm using Puppet Enterprise 2015.3.3 (I think these should be the relevant component versions: https://docs.puppetlabs.com/pe/latest/overview_version_table.html). And I'm (now) using v1.2.1 of this module (a3290fa).

I've attached a zip ([example.zip](https://github.com/cristifalcas/puppet-etcd/files/187074/example.zip)) with the working example I used to test/confirm the problem, but basically:
- site.pp does a hiera_include
- node yaml 'includes' profile::etcd wrapper class (roles coming later)
- wrapper class and hiera lookups do some parameter massaging
- wrapper class declares an etcd class resource with explicit parameters

node yaml from hiera: (names & values changed to protect the stupid)

```
classes:
  - profile::etcd

profile::etcd::initial_cluster: ... # magic and other parameters
```

profile/manifests/etcd.pp:

```
class profile::etcd(
    $ensure = 'present',
    $version = undef,
    # other ::etcd parameters, mostly required, some with undef default
) {
    validate_re($ensure, '^(present|absent)$')
    if $ensure == 'present' {
        $package_ensure = $version ? {
            undef   => 'latest',
            default => $version
        }
        $service_ensure = 'running'
        $service_enable = true
    } else {
        $package_ensure = 'purged'
        $service_ensure = 'stopped'
        $service_enable = false
    }

    class { '::etcd':
        ensure                      => $package_ensure,
        service_ensure              => $service_ensure,
        service_enable              => $service_enable,
        # all other ::etcd parameters, all one-to-one with the parameters
    }
}
```

profile/data/etcd.yaml:

```
# profile defaults including:
profile::etcd::cors: '*'
```

**Comment by cristifalcas** [comment]
@GKTheOne , can you check the new version? I modified the template to use scope everywhere

**Comment by GKTheOne** [comment]
Thanks Cristian, that works beautifully.
